services:
  nginx:
    image: nginx:latest
    container_name: dev_nginx
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build: ./php
    container_name: dev_php
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:11
    container_name: dev_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: Webtech
      MYSQL_USER: xzhuravel
      MYSQL_PASSWORD: 220606.Lilka
    volumes:
      - db_data:/var/lib/mysql
    

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: dev_phpmyadmin
    restart: always
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: xzhuravel
      PMA_PASSWORD: 220606.Lilka
    depends_on:
      - db

volumes:
  db_data: